sensor:
  ###############################################  Radarr ############################################### 
  - platform: radarr 
    api_key: !secret radarr_api_key
    host: !secret NAS_IP
    port: !secret radarr_port
    monitored_conditions:
      - upcoming
      - diskspace
      - status
      - movies
    unit: TB
    days: 30
  ############################################### This creates a sensor which shows the Playername(s) of Online Players ############################################### 
  - platform: template
    sensors:
      minecraft_server_players_online:
        friendly_name: "Who is Online?"
        value_template: "{{ state_attr('sensor.minecraft_server_players_online', 'players_list') }}"
  ############################################### System Monitor https://www.home-assistant.io/integrations/systemmonitor/ ###############################################
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: last_boot


############################################### For HACS Upcoming Media Card https://github.com/custom-cards/upcoming-media-card ###############################################
  - platform: plex_recently_added
    name: Recently Added Movies # will create sensor.recently_added_movies
    token: !secret plex_token
    host: !secret plex_host
    port: !secret plex_port
    max: 5 #Max number of items to show in sensor.
    section_types:
      - movie

  - platform: plex_recently_added
    name: Recently Added TV  # will create sensor.recently_added_tv
    token: !secret plex_token
    host: !secret plex_host
    port: !secret plex_port
    max: 5 #Max number of items to show in sensor.
    section_types:
      - show

  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_api_key
    host: !secret sonarr_host
    port: !secret sonarr_port
    days: 30 #How many days to look ahead for the upcoming sensor.
    ssl: false
    max: 5

  - platform: radarr_upcoming_media
    api_key: !secret radarr_api_key
    host: !secret radarr_host
    port: !secret radarr_port
    days: 365 #How many days to look ahead for the upcoming sensor.
    ssl: false
    theaters: true
    max: 5