- id: '1609101022114'
  alias: Nightly reboot at 01:45
  description: Reboot to keep HA fresh
  trigger:
  - platform: time
    at: 01:45
  - platform: tag
    tag_id: ''
  condition:
  - condition: time
    after: 01:30
    before: 02:00
  action:
  - service: homeassistant.restart
    data: {}
  mode: single
