#Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml

#Home Assistant URL
homeassistant:
  external_url: !secret external_url
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: !secret my_elevation
  unit_system: metric
  time_zone: !secret my_time_zone
  packages: !include_dir_named integrations

  #Themes
frontend:
  themes: !include_dir_merge_named themes

  # Text to speech
tts:
  - platform: google_translate


#Sensors
sensor:
  - platform: radarr ############################### Radarr
    api_key: !secret radarr_api_key
    host: !secret NAS_IP
    port: !secret radarr_port
    monitored_conditions:
      - upcoming
      - diskspace
      - status
      - movies
    unit: TB
    days: 30
  ############################################### This creates a sensor which shows the Playername(s) of Online Players
  - platform: template
    sensors:
      minecraft_server_players_online:
        friendly_name: "Who is Online?"
        value_template: "{{ state_attr('sensor.minecraft_server_players_online', 'players_list') }}"

# Binary Sensors
binary_sensor:
  - platform: rest
    name: Daves Room motion
    device_class: motion
    resource: http://192.168.1.143:8080/sensors.json?sense=motion_active
    value_template: "{{ value_json.motion_active.data[0][1][0] | round(0) }}"

#Lightgroup
light:
  - platform: group
    name: all the lights
    entities:
      - light.dave
      - light.esszimmer
      - light.gang
      - light.nachttisch
      - light.schlafzimmer
      - light.wohnzimmer
      - light.badezimmer_1
      - light.badezimmer_2


#Minecraft Stuff
#minecraft:
#  host: 192.168.1.124
#  query_port: !secret mc_query_port
#  rcon_port: !secret mc_rcon_port
#  rcon_password: !secret mc_rcon_password
#  notify: true # (Default: true, set to false to remove notify services)
#  icon: mdi:minecraft # (Default: mdi:minecraft)
#  name: sensor.gsb_minecraft_server # (Default: Minecraft Server (sensor.minecraft_server))
#  sensor: # List of default sensors
#    - motd
#    - game_type
#    - version
#    - map
#    - players
#    - type #optional sensor
#    - session_id #optional sensor
#    - host_name #optional sensor
#    - game_id #optional sensor
#    - plugins #optional sensor
#    - num_players #optional sensor
#    - max_players #optional sensor
#    - host_port #optional sensor
#    - host_ip #optional sensor

###############################################################################
# from Here on out, this stuff needs HACS
###############################################################################

#Spotcast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

# Xiaomi Roborock S5 Cloud Map Extractor
camera:
  - platform: xiaomi_cloud_map_extractor # https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
    host: !secret roborock_s5_ip
    token: !secret roborock_s5_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: "de"
    name: "Roborock S5"
    draw: ["all"]
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    map_transformation:
      scale: 1.5
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20

