#Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml

#Home Assistant URL
homeassistant:
  internal_url: !secret internal_url
  external_url: !secret external_url
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: !secret my_elevation
  unit_system: metric
  time_zone: !secret my_time_zone
  packages: !include_dir_named integrations

  #Themes
frontend:
  themes: !include_dir_merge_named themes

  # Text to speech
tts:
  - platform: google_translate

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

  ############################################################################################################################
  ##### The config file is very empty, because the config is split
  ##### See /integrations folder
  ##### This gave me the idea: https://www.youtube.com/watch?v=kgFwhYInzfA&t=809s
  ##### This seems to be useful https://www.home-assistant.io/docs/configuration/splitting_configuration/
  ############################################################################################################################
