#Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml

#Home Assistant URL
homeassistant:
  external_url: !secret external_url
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: !secret my_elevation
  unit_system: metric
  time_zone: !secret my_time_zone
  packages: !include_dir_named integrations

  #Themes
frontend:
  themes: !include_dir_merge_named themes

  # Text to speech
tts:
  - platform: google_translate